/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'message' : [] | [string],
  'preferredDate' : string,
  'preferredTime' : string,
  'category' : BookingCategory,
  'phoneNumber' : string,
}
export type BookingCategory = { 'appointment' : null } |
  { 'homeTour' : null } |
  { 'nameChange' : null };
export type BookingError = { 'invalidInput' : null } |
  { 'internalError' : null };
export interface BookingRequest {
  'customerName' : string,
  'serviceType' : ServiceType,
  'message' : [] | [string],
  'preferredDate' : string,
  'preferredTime' : string,
  'category' : BookingCategory,
  'phoneNumber' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'confirmed' : null };
export type ServiceType = { 'tarotCardReading' : null } |
  { 'vastu' : null } |
  { 'numerology' : null } |
  { 'pronology' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [BookingRequest],
    { 'ok' : Booking } |
      { 'err' : BookingError }
  >,
  'deleteAllBookings' : ActorMethod<[], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTotalBookingCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];