/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'tarotCardReading' : IDL.Null,
  'vastu' : IDL.Null,
  'numerology' : IDL.Null,
  'pronology' : IDL.Null,
});
export const BookingCategory = IDL.Variant({
  'appointment' : IDL.Null,
  'homeTour' : IDL.Null,
  'nameChange' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'category' : BookingCategory,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [
        ServiceType,
        BookingCategory,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'tarotCardReading' : IDL.Null,
    'vastu' : IDL.Null,
    'numerology' : IDL.Null,
    'pronology' : IDL.Null,
  });
  const BookingCategory = IDL.Variant({
    'appointment' : IDL.Null,
    'homeTour' : IDL.Null,
    'nameChange' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'category' : BookingCategory,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [
          ServiceType,
          BookingCategory,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };