/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'tarotCardReading' : IDL.Null,
  'vastu' : IDL.Null,
  'numerology' : IDL.Null,
  'pronology' : IDL.Null,
});
export const BookingCategory = IDL.Variant({
  'appointment' : IDL.Null,
  'homeTour' : IDL.Null,
  'nameChange' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : ServiceType,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'category' : BookingCategory,
  'phoneNumber' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'message' : IDL.Opt(IDL.Text),
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
  'category' : BookingCategory,
  'phoneNumber' : IDL.Text,
});
export const BookingError = IDL.Variant({
  'invalidInput' : IDL.Null,
  'internalError' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [BookingRequest],
      [IDL.Variant({ 'ok' : Booking, 'err' : BookingError })],
      [],
    ),
  'deleteAllBookings' : IDL.Func([], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTotalBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'tarotCardReading' : IDL.Null,
    'vastu' : IDL.Null,
    'numerology' : IDL.Null,
    'pronology' : IDL.Null,
  });
  const BookingCategory = IDL.Variant({
    'appointment' : IDL.Null,
    'homeTour' : IDL.Null,
    'nameChange' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : ServiceType,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'category' : BookingCategory,
    'phoneNumber' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'message' : IDL.Opt(IDL.Text),
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
    'category' : BookingCategory,
    'phoneNumber' : IDL.Text,
  });
  const BookingError = IDL.Variant({
    'invalidInput' : IDL.Null,
    'internalError' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [BookingRequest],
        [IDL.Variant({ 'ok' : Booking, 'err' : BookingError })],
        [],
      ),
    'deleteAllBookings' : IDL.Func([], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTotalBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };